### ISSUE TITLE
Disabled Buttons Styles

### ISSUE THREAD

**Issue by rich-martinez** [ScalesCSS/patterns-buttons#1]
Should disabled buttons have a hover state?
You could possibly use pointer-events: none. Staying consistent with Scales, it is supported in IE9+. 

On a similar note: 
Should .btn.is-disabled have a background property, and color property? 
When using those classes on an input, input.is-disabled overwrites the .btn colors, and it is not consistent with the other types of disabled buttons.

**Comment by yodasw16** [comment]
I think you are right about using `pointer-events: none` to disable the hover states, but I'm not sure I understand the second part.

`.is-disabled` doesn't have color or background properties set. They are inherited form `.btn`, yes, but if that weren't the case the background color would have to be set to initial to "reset" it and then it would just be white, which doesn't really convey "disabled". A disabled button should still have a background color, but be visually lighter. I used opacity to control that, and I think that works.

**Comment by yodasw16** [comment]
Closed by https://github.com/ScalesCSS/patterns-buttons/commit/c058f56ec52ea54e5d8d25fcbddff28be2fc5cd2

**Comment by rich-martinez** [comment]
I am a bit confused now, so to be clear, the following illustrates what I am experiencing.

[disabled buttons](http://sassmeister.com/gist/045e3ea24566d1babecf)

This is what it is like by default. Where the button inputs that have .is-disabled classes (and .btn classes) are receiving their color related styles from input.is-disabled, and not the .btn class. Is it supposed to be that way?

If not, what about trying:

input[disabled]:not(.#{$scales-namespace}btn),
select[disabled],
textarea[disabled],
input.is-disabled:not(.#{$scales-namespace}btn),
select.is-disabled,
`textarea.is-disabled {
    cursor: not-allowed;
    border-color: $input-disabled-border-color;
    background-color: $input-disabled-background-color;
    color: $input-disabled-text-color;
}`

OR

`input.#{$scales-namespace}btn:disabled, 
input.#{$scales-namespace}btn.is-disabled{
       border-color: $btn-border-color;
       background-color: $btn-background-color;
       color: $btn-text-color;
}`

**Comment by yodasw16** [comment]
Sorry, I ended up finding the problem. There is a conflict with forms. I think I fixed it here https://github.com/ScalesCSS/patterns-buttons/commit/070fb0daac61366fca4ecdb715c677a2622802d5

**Comment by rich-martinez** [comment]
Cool! :+1: 

I think you would still need to add border-color on .#{$scales-namespace}btn.is-disabled. I didn't notice it before.

**Comment by yodasw16** [comment]
Dang, yeah...I see that now too. I'll add border-color as well. thanks!
